routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/user_detail', 'HomeController@showUserDetail')-> name('user_detail');


Route::get('/ajax',function() {
    return view('pages.message');
 });
// Route::post('/delete',['uses' => 'TelephoneController@destroy', 'as' => 'delete']);
Route::post('/getmsg',['uses' => 'AjaxController@index', 'as' => 'getmsg']);

Route::get('/live_search', 'AjaxController@liveSearch')->name('live_search');
Route::get('/live_search/action', 'AjaxController@action')->name('live_search.action');
Route::get('/delete/{id}', 'AjaxController@deleteUser')->name('user.delete');
Route::get('{id}/view_user', 'AjaxController@viewUser')->name('user.view');

Route::group(['prefix' => 'profile', 'as'=>'profile.'], function(){
    Route::get('/profile/view', ['uses' => 'ProfileController@myProfile','as' => 'view']);
});

Route::get('/comment_count', function(){
    return view('pages.jQuery.comment_count');
});
Route::get('/Style', function(){
    return view('pages.jQuery.style_methods');
});

Route::get('/scoreboard', function(){
    return view('pages.jQuery.scoreboard');
});
Route::get('/php_function', function(){
    return view('pages.test.static_function');
});

Route::get('test', function () {
    throw new \Exception('First Exception detected');
});

Route::get('game', function (){
    return view('pages.dinosaur.game');
});

Route::get('pusher','MessageController@index')->name('pusher');
Route::get('sender','MessageController@getSender')->name('sender');
Route::post('sender','MessageController@postSender')->name('sender');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AjaxController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AjaxController extends Controller
{
    public function index(Request $request){
        // dd($request);
        // $msg = $request;
        $msg = Auth::user();
        // dd($msg);
        return response()->json(array('msg'=> $msg), 200);
    }

    public function liveSearch()
    {
        return view('pages.live_search');
    }

    public function action(Request $request)
    {
        // dd($request->all());
     if($request->ajax())
     {
      $output = '';
      $query = $request->get('query');
      if($query != '')
      {
       $data = User::where('name', 'like', '%'.$query.'%')
         ->orWhere('email', 'like', '%'.$query.'%')
         ->orWhere('created_at', 'like', '%'.$query.'%')
         ->orWhere('updated_at', 'like', '%'.$query.'%')
         ->orderBy('name', 'desc')
         ->get();
      }
      else
      {
       $data = User::get();
      }

      $total_row = $data->count();

    //   if($total_row > 0)
    //   {
    //    foreach($data as $row)
    //    {
    //     $output = '
    //     <tr>
    //      <td>'.$row->name.'</td>
    //      <td>'.$row->email.'</td>
    //      <td>'.$row->created_at.'</td>
    //      <td>'.$row->updated_at.'</td>
    //      <td>
    //         <a class="btn btn-sm btn-danger" href="home" >Delete</a>
    //      </td>
    //     </tr>
    //     ';
    //    }
    //   }
    //   else
    //   {
    //    $output = '
    //    <tr>
    //     <td align="center" colspan="5">No Data Found</td>
    //    </tr>
    //    ';
    //   }
      $data1 = array(
       'table_data'  => $data,
       'total_data'  => $total_row
      );
    //   dd($data);

      echo json_encode($data1);
     }
    }

    public function deleteUser($id){
        $user = User::find($id);
        if (isset($user)){
            $user->delete();

            return redirect()->back();
        }
        else {
            echo "Nothing to delete";
        }
        // dd($user);
    }

    public function viewUser($id){
        $user_data = User::find($id);
        // dd($user_data);
        return view('pages.user-profile')->with('user_data', $user_data);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FileUploadController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FileUploadController extends Controller
{
    function index(){
        return view('file_upload');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        $users = User::orderBy('name', 'ASC')->get();
//        dd($users);
        return view('home')->with('users', $users);
    }

    public function showUserDetail(Request $request){

        $user_detail = User::where('id', $request->id)->orderBy('id', 'DESC')->first();
//        dd($user_detail);
        return ($user_detail);
    }
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Events\MessageSent;
use Illuminate\Http\Request;

class MessageController extends Controller
{
    public function index(){
//        dd("index");
        return view('pages.pusher.pusher');
    }

    public function getSender(){
        return view('pages.pusher.sender');
    }

    public function postSender(Request $request){

        $text = $request['content'];
//        dd(new MessageSent(($text)));
//        dd(event(new MessageSent($text)),"-",$request->all());
//        dd($text);
        event(new MessageSent($text));

//        dd($request->all());
        return back();
    }



}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProfileController extends Controller
{
    public function myProfile(){
        return view('pages.my_profile');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">

            <div class="row col-md-12">
                <div class="card col-md-8">
                    <div class="card-header">User Details from Controller</div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Created At</th>
                                <th>Updated At</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->created_at }}</td>
                                    <td>{{ $user->updated_at }}</td>
                                    <td>
                                        <a href="#" class="btn btn-sm btn-outline-danger">Delete</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card col-md-4">
                    <div class="card-header">User Details with Ajax(POST)</div>
                    <div class="card-body">
                        {{--                        Select user--}}
                        <div class="form-group">
                            <label>Select User Name:</label>

                            <select class="form-control" name="user" id="user">
                                <option>-- SELECT USER --</option>
                                @if (!empty($users))
                                    @foreach ($users as $data)
                                        <option value={{ $data->id }}>{{$data->name}}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>

                        {{--List user Detail--}}

                        <div class="form-group"  id="userDetail" style="display: none;">
                        <form method="" action="">
                            <div id="append">
                                    <label class="control-label">User Details</label>
                                        <ul>
                                        {{-- User Detail is listed here using js/Ajax --}}
                                        </ul>

                            </div>
                            <a href="" onclick="alert('Thank You'); return false; " class="btn btn-sm btn-primary">Update</a>
                        </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="{{asset('public/js/jquery.min.js')}}"></script>

    <script>
        $(document).ready(function (){
            $("#user").on ('change',  function(){
                //fetches selected "user id" and stores in "user_id"
                let user_id = $('#user').val();
                // console.log(user_id);

                // removes previous data from list-view
                $("#append").children("li").remove();

                //retrieving assigned user from task id.
                $.ajax({
                    type: "post",
                    url: "{{ route('user_detail') }}",
                    headers: {
                        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                    },

                    data: "id=" + user_id,

                    // gets data from getAssignedUserByTaskId() in var 'msg'
                    success: function (user_detail) {
                        // console.log(user_detail);
                        $('#userDetail').show();

                        $("#append").append("<li>Name:" + user_detail.name +"</li>");
                        $("#append").append("<li>Email:&nbsp" + user_detail.email +"</li>");
                        $("#append").append("<li>Join Date : " + user_detail.created_at +"</li>");
                        $("#append").append("<li>Update Date : " + user_detail.updated_at +"</li>");
                        $("#append").append("<li>Email Verification Date : " + user_detail.email_verified_at +"</li>");


                    }
                });
            });

        });
    </script>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('public/js/app.js') }}" defer></script>
    {{-- jquery used in my-profile --}}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

   <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('public/css/app.css') }}" rel="stylesheet">

    {{-- hover DropDown --}}
   <style>
        .dropdown:hover > .dropdown-menu {
            display: block;
        }
        .dropdown > .dropdown-toggle:active {
            /*Without this, clicking will make it sticky*/
            pointer-events: none;
        }
    </style>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link btn btn-sm btn-link" href="{{ url('php_function') }}">Php Function</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-sm btn-outline-primary" href="{{ route('live_search') }}">Ajax-Search</a>
                    </li>
                    &nbsp;
                    <li class="nav-item">
                        <a class="nav-link btn btn-sm btn-outline-warning" href="{{url('ajax')}}">Ajax &nGg;</a>
                    </li>
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register App.') }}</a>
                            </li>
                        @endif
                    @else
                        {{-- Create New user --}}
                        <li class="nav-item">
                            <a class="nav-link " href="{{ route('register') }}">{{ __('Create New User') }}</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle btn btn-sm btn-outline-success" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                {{-- My-Profile --}}
                                <a class="dropdown-item" href="{{ route('profile.view') }} ">My Profile</a>
                                {{-- Home --}}
                                <a class="dropdown-item" href="{{ route('home') }}">Home</a>
                                <a class="dropdown-item" href="{{ url('Style') }} ">Style Methods</a>
                                <a class="dropdown-item" href="{{ url('scoreboard') }} ">ScoreBoard</a>
                                {{-- jquery comment count --}}
                                <a class="dropdown-item" href="{{ url('/comment_count') }} ">Comment Count</a><hr>
                                {{-- Log Out --}}
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>

                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
@yield('script')
</body>
</html>

resources/views/pages/dinosaur/game.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Inspector Dashboard</title>
    <link rel="icon" href="https://app.inspector.dev/images/favicon.png" type="image/png" />

    <!-- CSRF Token -->
    <meta name="csrf-token" content="JnXwohdZ40UTXFg7t0CWQ71HZlOtwgkUjNkqwR4p">

    <!-- Social share style -->
    <meta property="og:image" content="https://app.inspector.dev/images/frontend/dashboard.png"/>
    <meta property="og:title" content="Get free real-time monitoring & alerting."/>
    <meta property="og:url" content="https://app.inspector.dev/register"/>
    <meta property="og:description" content="Get instant alerts if your back-end fails and identify issues at a glance before users are aware of them."/>
    <meta property="og:type" content="article"/>

    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:image" content="https://app.inspector.dev/images/frontend/dashboard.png"/>
    <meta name="twitter:title" content="Get free real-time monitoring & alerting."/>
    <meta name="twitter:url" content="https://app.inspector.dev/register"/>
    <meta name="twitter:description" content="Get instant alerts if your back-end fails and identify issues at a glance before users are aware of them."/>

    <!-- Styles -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="/css/style.css?id=b640de9a345f792f5da9" rel="stylesheet">

    <!-- Facebook Pixel Code -->
    <script>
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window,document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '731890293828657');
        fbq('track', 'PageView');
    </script>
    <noscript>
        <img height="1" width="1" src="https://www.facebook.com/tr?id=731890293828657&ev=PageView&noscript=1"/>
    </noscript>
    <!-- End Facebook Pixel Code -->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-135189893-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-135189893-1');
    </script>

    <script src="https://js.stripe.com/v3/"></script>
    <script>
        window.Organization = {"id":380,"name":"technology sales","email":"lostinecho2070@gmail.com","address":null,"city":null,"zip_code":null,"country":null,"vat":null,"current_usage":"0","referral_link":"https:\/\/app.inspector.dev\/register?referrer=5de6109410564","referrals_count":0,"created_at":"2019-12-03 07:36:52","updated_at":"2019-12-03 07:36:52"};
    </script>

    <script>
        fbq('track', 'CompleteRegistration');
    </script>

    <!-- Hotjar Tracking Code for https://www.inspector.dev -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:1049507,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

    <!-- Customerly live chat -->
    <script>
        window.customerlySettings = {
            app_id: "06efa3b2",
            user_id: "412",// Optional
            name: "Mukesh Rai",
            email: "lostinecho2070@gmail.com",

            //If you manage different user companies you can track the companies and their attributes like this:
            company: {
                company_id: "380",
                name: "technology sales",
            }
        };
        !function(){function e(){var e=t.createElement("script");e.type="text/javascript",e.async=!0,e.src="https://widget.customerly.io/widget/06efa3b2";var r=t.getElementsByTagName("script")[0];r.parentNode.insertBefore(e,r)}var r=window,t=document,n=function(){n.c(arguments)};r.customerly_queue=[],n.c=function(e){r.customerly_queue.push(e)},r.customerly=n,r.attachEvent?r.attachEvent("onload",e):r.addEventListener("load",e,!1)}();
    </script>
</head>
<body style="height: 100vh">
<div id="app" style="height: 100%">

    <App :user="{&quot;id&quot;:412,&quot;name&quot;:&quot;Mukesh Rai&quot;,&quot;email&quot;:&quot;lostinecho2070@gmail.com&quot;,&quot;email_verified_at&quot;:&quot;2019-12-03 07:36:52&quot;,&quot;is_org_admin&quot;:true,&quot;created_at&quot;:&quot;2019-12-03 07:36:52&quot;,&quot;updated_at&quot;:&quot;2019-12-03 07:36:52&quot;,&quot;deleted_at&quot;:null,&quot;organization_id&quot;:380,&quot;organization&quot;:{&quot;id&quot;:380,&quot;name&quot;:&quot;technology sales&quot;,&quot;email&quot;:&quot;lostinecho2070@gmail.com&quot;,&quot;address&quot;:null,&quot;city&quot;:null,&quot;zip_code&quot;:null,&quot;country&quot;:null,&quot;vat&quot;:null,&quot;created_at&quot;:&quot;2019-12-03 07:36:52&quot;,&quot;updated_at&quot;:&quot;2019-12-03 07:36:52&quot;,&quot;deleted_at&quot;:null,&quot;stripe_id&quot;:null,&quot;card_brand&quot;:null,&quot;card_last_four&quot;:null,&quot;trial_ends_at&quot;:null,&quot;locked_at&quot;:null,&quot;referral_code&quot;:&quot;5de6109410564&quot;,&quot;referred_by&quot;:null,&quot;subscriptions&quot;:[]}}">
        <!--placeholder to show while App component is loading on page for the first time-->
        <VSpinner/>
    </App>

</div>

<!-- Scripts -->
<script src="/js/manifest.js?id=89712bc6d8c588400cae"></script>
<script src="/js/vendor.js?id=00a21643656954df75c4"></script>
<script src="/js/app.js?id=dbae03547245f8f0054a" defer></script>
</body>
</html>

resources/views/pages/file/file_upload.blade.php
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laravel 5.8 - File Upload with Progressbar using Ajax jQuery</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>
</head>
<body>
<div class="container">
    <br />
    <h3 align="center">Laravel 5.8 - File Upload with Progressbar using Ajax jQuery</h3>
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">File Upload with Progressbar using Ajax jQuery</h3>
        </div>
        <div class="panel-body">
            <br />
            <form method="post" action="{{ route('upload') }}" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-md-3" align="right"><h4>Select Image</h4></div>
                    <div class="col-md-6">
                        <input type="file" name="file" id="file" />
                    </div>
                    <div class="col-md-3">
                        <input type="submit" name="upload" value="Upload" class="btn btn-success" />
                    </div>
                </div>
            </form>
            <br />
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow=""
                     aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                    0%
                </div>
            </div>
            <br />
            <div id="success">

            </div>
            <br />
        </div>
    </div>
</div>
</body>
</html>

<script>
    $(document).ready(function(){

        $('form').ajaxForm({
            beforeSend:function(){
                $('#success').empty();
            },
            uploadProgress:function(event, position, total, percentComplete)
            {
                $('.progress-bar').text(percentComplete + '%');
                $('.progress-bar').css('width', percentComplete + '%');
            },
            success:function(data)
            {
                if(data.errors)
                {
                    $('.progress-bar').text('0%');
                    $('.progress-bar').css('width', '0%');
                    $('#success').html('<span class="text-danger"><b>'+data.errors+'</b></span>');
                }
                if(data.success)
                {
                    $('.progress-bar').text('Uploaded');
                    $('.progress-bar').css('width', '100%');
                    $('#success').html('<span class="text-success"><b>'+data.success+'</b></span><br /><br />');
                    $('#success').append(data.image);
                }
            }
        });

    });
</script>

resources/views/pages/live_search.blade.php
@extends('layouts.app')

@section('content')

  <div class="container box">
   <h3 align="center">Live search in laravel using AJAX</h3><br />
   <div class="panel panel-default">

    <div class="panel-heading">Search Customer Data</div>
    <div class="panel-body">
     <div class="form-group">
      <input type="text" name="search" id="search" class="form-control" placeholder="Search Customer Data" />
     </div>

     <div class="table-responsive">
         {{-- Total data count --}}
      <h3 align="center">Total Data : <span id="total_records"></span></h3>

      <table class="table table-striped table-bordered" >
       <thead>
        <tr>
         <th>Name</th>
         <th>Email</th>
         <th>Join Date</th>
         <th>Update Date</th>
         <th>Action</th>
        </tr>
       </thead>
       <tbody id="table-data">
           <a id="href" href="#">
            <tr>
                <a href="#"></a>
                {{-- <input type="text" id="user_id"> --}}
                {{-- <td id="name"></td>
                <td id="email"></td>
                <td id="join_date"></td>
                <td id="update_date"></td> --}}
            </tr>
           </a>

       </tbody>
      </table>
      {{-- <ul id="data-list">
      </ul> --}}
     </div>
    </div>
   </div>
  </div>

@endsection

@section('script')
<script>
        $(document).ready(function(){

         fetch_customer_data();

         function fetch_customer_data(query = '')
         {
          $.ajax({
           url:"{{ route('live_search.action') }}",
           method:'GET',
           data:{query:query},
           dataType:'json',
           success:function(data)
           {
            //    console.log(data.table_data);
            $("#table-data").children(["tr","td"]).remove();


            $.each(data.table_data, function () {
                var id = this.id;
                // alert(id);
                var newRowContent = "<tr><td>" + this.name +"</td><td>" + this.email + "</td><td>" + this.created_at + "</td><td>" + this.updated_at + "</td><td><a class='btn btn-sm btn-primary' href='http://localhost/Ajax/"+this.id+"/view_user/' >view</a> <a class='btn btn-sm btn-danger' href='http://localhost/Ajax/delete/"+this.id+"'>Delete</a></td></tr>";
                $('#table-data').append(newRowContent);

                // $("#table-data").append("<input type='text' value=" + this.id + ">");

                // $("#email").html(this.email);
                // $("#join_date").html(this.created_at);
                // $("#update_date").html(this.updated_at);

                console.log(this.name);

            })


                // $('#table-data').append("<td>" + this.email +"</td>");

            $('#total_records').text(data.total_data);
            }
            })
            }
        // })

         $(document).on('keyup', '#search', function(){
          var query = $(this).val();
          fetch_customer_data(query);
         });
        });
</script>

@endsection

resources/views/pages/pusher/sender.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Send Message</title>
</head>
<body>
<h1>Send Your Message through Pusher</h1>

<div>
    <form action="{!! route('sender') !!}" method="post">
        @csrf
        <label>Your Message:</label><br>
        <textarea type="text" name="content" cols="40" rows="5" placeholder="your message..."></textarea><br>
        <button type="submit" style="height: 50px; width: 100px; background: steelblue; font-size: 16px;">SUBMIT</button>
    </form>

</div>
<div id="message">

</div>


</body>
</html>